steps:

- name: 'gcr.io/cloud-builders/kubectl'
  id: Deploy
  args:
  - 'apply'
  - '- f'
  - 'kube-deployment.yml'
options:
  logging: CLOUD_LOGGING_ONLY

  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=demo1'
