apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-webapp
  name: nginx-webapp
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx-webapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-webapp
    spec:
      containers:
      # - image: gcr.io/staticweb-test/nginx-webapp:v1
      - image: gcr.io/ic-int-sandbox-tarique/nginx
        name: webapp
        imagePullPolicy: Always
        # env:
        #   - name: HTTP_PORT
        #     valueFrom:
        #       configMapKeyRef:
        #         key: http_port
        #         name: {{.BackendID}}
        resources: {}
        ports:
          - containerPort: 80 
status: {}
